In [1]:
import numpy as np

## 1. Create a null vector of size 10 but the fifth value which is 1.

In [5]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## 2. Create a vector with values ranging from 10 to 49.

In [9]:
vector = np.arange(10, 50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## 3. Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [12]:
arr = np.array([1,2,0,0,4,0])
non_zero_indices = np.nonzero(arr)
non_zero_indices

(array([0, 1, 4], dtype=int64),)

## 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [14]:
random_array = np.random.rand(10,10)

min_value = np.min(random_array)
max_value = np.max(random_array)

print("Minimum Value:", min_value)
print("Maximum value:", max_value)

Minimum Value: 0.004845045522431701
Maximum value: 0.9939253232394376


## 6. Create a random vector of size 30 and find the mean value.  

In [16]:
random_vector = np.random.rand(30)

mean_value = np.mean(random_vector)
print("Mean Value:", mean_value)

Mean Value: 0.5271831437536123
